#----------------------------------------------------------------------
# This file was generated by /usr/local/bin/img2py
#
# Icons from Silk Icon Set
# Mark James
# http://www.famfamfam.com/lab/icons/silk/
from extern.embeddedimage import PyEmbeddedImage

Brick = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAntJ"
    "REFUOI2lkz9ILHcQxz/779TD271FOPGp6VQk2Fnb+eCRUlI8CCkf+ITYhtcnkCa9NgELc4de"
    "ldrGziouKiIXZaOnIHjuLXp67t5vJpXHe8ZU+VTDzBfmO8OMxSvs7u7+3G63v0+S5A1AGIZX"
    "5XJ5Y2Fh4dNr+i+o1+uVWq2W6QtqtVq2ubn55qXeeu6Ypun7JEm+AuwgCJiammJmZgZV5fj4"
    "mLOzM9I0BZAwDM+DIPi976harXY/7xbHsW5vb2sURRpFkW5tbWkcx184qlarXQCnXq//5rru"
    "vKoyMjKCqnJyckKv1yOOY66vr/F9H2MMY2NjiAhHR0ekaeouLi7OuCLy3dzcHJ1OhyiKcByH"
    "y8tLlpaWXu6GYrFInud0Oh3K5TKtVutbG+iMj48zMTFBEASUSiUqlQqNRgMRQURoNBqMjo5S"
    "KBRIkoQsywjDEFXtuKoKwODgIJ7ncXd3h+d5pGnK4eEhAHmec3t7S7fbxfM8AFQVVcUVkX5C"
    "RBgaGmJycpKHhwdEhJubGx4fHymVSriui2VZGGMwxiAiuMaYIdu2UVXyPMcYQ57nWJaFiNDr"
    "9RgYGOjvIsuyfk1EBm1gd29vjzRNKRaLOI6DiPA82nOsqjw9PeH7PrZtc3p6iojs2Z7nfXNx"
    "cfFhZ2fnr/39fSzLwvd9XNcFwBhDlmUUi0WGh4eJ45iDg4O/W63WD4VC4Z31bG1jY6OS5/mq"
    "qn6cnZ0tT09PY4yh2WxiWRZXV1ecn5/fq+q64zi/Li8vX/ZP+XPW19e/Bj6p6vv5+Xmr3W7T"
    "bDa5v7+v93q9n1ZXV//81y+8xtra2lsR+VFECsAvKysrf/yX9n/xD16Kioq/LFKkAAAAAElF"
    "TkSuQmCC")
getBrickData = Brick.GetData
getBrickImage = Brick.GetImage
getBrickBitmap = Brick.GetBitmap

#----------------------------------------------------------------------
Brick_Add = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAuJJ"
    "REFUOI11kk9oHGUYxn/f7Eyy+TO7O4lskibxoIQosq3CWkor8RBWBEUPi4GCGPTgodCTl9CL"
    "t9KL10IiWPCQ7pIsUgiCQhCCCBb/ZCQhTXZJt8aUTUgyO91uMs7s932eGuxaf8eXh+d53pdX"
    "8AxWVlau1+v1jzzPOwPgOM7DVCr19cTExLVn6Z+iVCqli8ViqNsoFovh/Pz8mXa9eJLo+/5l"
    "z/OeB4xkMsnY2Bjj4+NordnY2GB7exvf9wGU4zh/JpPJ26eNCoVC8O+0arWqFxcXteu62nVd"
    "vbCwoKvV6lONCoVCABArlUq3TNPMaq3p7+9Ha83m5iatVotqtcre3h6JRAIpJUNDQyilWF9f"
    "x/d9M5fLjZtKqQ8zmQzNZhPXdYnFYuzu7pLP59tvQ3d3N1EU0Ww2SaVSHB4efmAAzeHhYUZG"
    "Rkgmk9i2TTqdplwuo5RCKUW5XGZgYICOjg48zyMMQxzHQWvdNLXWAMTjcSzLotFoYFkWvu+z"
    "trYGQBRFHB0dEQQBlmUBoLVGa42plDodKKXo6upidHSU4+NjlFIcHBxwcnKCbduYpokQAikl"
    "UkqUUphSyi7DMNBaE0URUkqiKEIIgVKKVqtFZ2cn9/Z/5d7+bzwOHhH8fUJm+ALdaiAey+fz"
    "b/q+/0JPTw+9vb1IKQnD8HT/RqPBWu1n9sU6l7LnmXz9bQJrn7sPvuOv2sOaYVnWOzs7O58u"
    "Ly9XVldXEUKQSCQwTRMAKSW/PPiBV186hzQk54ZySBFxIXORiu8+Z0xNTYXT09NfGoZxqVKp"
    "XF9aWqpvbW1h2zZ9fX04jsPBoz0s0ct7L18F4LPJOV5Mn0Ug4qL9t+fm5l4BrmmtL2ezWVGv"
    "1/n8zie8/+4kLRQzuVvc+P5j4rFObn9zJ/iPwRNmZ2ffUkrNKKU6vr3/1W58sDl18ewbjA2+"
    "Rrn2Oz/98SM79/0v/tegnfNXBm8gxBUBtoYGWt+8e7M28w+rNJghLvXdJQAAAABJRU5ErkJg"
    "gg==")
getBrick_AddData = Brick_Add.GetData
getBrick_AddImage = Brick_Add.GetImage
getBrick_AddBitmap = Brick_Add.GetBitmap

#----------------------------------------------------------------------
Brick_Bricks = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAr5J"
    "REFUOI2Vk89rHGUYxz/7zsz+KpvZcXFDupuKxXQrEgXRg5fgJRT1GDwoUkQ0GA8KHvsH9N5T"
    "IQcLQeIuyYrgJVhDa7DC3jIkS0g3idOGbRvtZna6nWSZd+d9PXVpQ0H6OT48z/N9fiZ4Dmtr"
    "a5e73e5F3/dPAziOcy+fzy9MTU1dep7/M9Tr9WKtVov0CWq1WrS4uHj6pH/iiWIQBJ/4vn8G"
    "ELZtMzExQaVSQWvN1tYWe3t7BEEAoBzHuWvb9k/DiqrVav9pNc/z9PLysnZdV7uuq5eWlrTn"
    "ec9UVK1W+wBGvV6/ZprmO1prCoUCWmu2t7cZDAZ4nsfBwQEjIyPEcczY2BhKKZrNJkEQmNPT"
    "0xVTKfXZ5OQkYRjiui6GYdBut5mZmTk5G7LZLFJKwjAkn8/T6XQ+FkBYKpUol8vYtk0ul6NY"
    "LNJqtVBKoZSi1WoxOjpKMpnE932iKMJxHLTWoam1BiCdTmNZFr1eD8uyCIKAzc1NAKSUHB4e"
    "0u/3sSwLAK01WmtMpdTQoJQik8kwPj7O0dERsttF31yleLtFScV0zr+O/+ZbxOkMcRyjlELE"
    "cZwRQiCEQEpJFEVIKTmWkgcrP/KqSCFSSURuhPFuj8xffwxbU0qlBbDWaDQIgoBsNothGFy9"
    "cYXf7v/Cw8f3SJ07j/VSARX49B/scyqTRQjB7u4uSqmGsCzro/39/dnV1dWd9fV1EokEfx/v"
    "8Hb5XcLKWfxfl0naeUw5YPDoX36PX2ZjY+NOp9P5NplMfpB4sqaFhYWilPI7rfU3N+VK/ov3"
    "v8I/7vDzrTt8Hpj881jSeOU9TmVTnDlyy3Nzc+3hKT/N/Pz8G8Cl3aj1aa6cYuN2mq8//JKd"
    "9kP+XL+LYRn88P2FYZw4mWB2drZ5PX/94lnrtQuF+6UbFV3cXLnVJAE6RtDzH/3vQ74Q/wH5"
    "/YjwPclljgAAAABJRU5ErkJggg==")
getBrick_BricksData = Brick_Bricks.GetData
getBrick_BricksImage = Brick_Bricks.GetImage
getBrick_BricksBitmap = Brick_Bricks.GetBitmap

#----------------------------------------------------------------------
Brick_Go = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAtVJ"
    "REFUOI2Nk01oXGUUhp/5y8/QzJ1pyqRJJsVUh2EsQRdKBDELa4IguAkFFWkXCoIobsSf0o2g"
    "FruvkNkIWcQZklkrRUGzKAQVGUgax5F0OkPSBok31+lNZ+53v3NcpdjYhc/y8HLel/NyIjyE"
    "1dXVz/f398+7rjsGkMlkdtLp9OLMzMzFh+kfoFqtZiuVSqBHqFQqwdLS0thRfeTQ0fO8V13X"
    "PQVEHcchn89TKBRQVTY3N9na2sLzPADJZDItx3G+vp+oXC53/+3WbDZ1ZWVFa7Wa1mo1XV5e"
    "1maz+UCicrncBYhVq9Wv4vH4U6rK8PAwqkq9XicMQ5rNJru7u6RSKay1jI6OIiJsbGzgeV58"
    "dna2EBeR16empvB9n1qtRiwWY3t7m/n5+aO3IZlMYozB933S6TR7e3vnooA/Pj5OLpfDcRyG"
    "hobIZrM0Gg1EBBGh0WgwMjJCX18frusSBAGZTAZV9eOqCsDAwACJRIJOp0MikcDzPNbX1wEw"
    "xrB862Pu/eHzyiNXiEUSqCqqSlREAFBVRITBwUEmJiZwHIf+/n46nQ6u69ILDbkTRUr1dwkl"
    "wFqLiBC31g5Go1FUFWMM1lqMMVz96Q1UDIGEBGHI2PE8xZPTdLo+V2rnuTRdRkQG4sDq2tra"
    "C/l8nlQqxcHBAb1ej1ACZs9cwKpgxSIoO16bqdyz3A3u8f6PL3Lu2Ce/xBOJxEvtdvtCq9X6"
    "YHJy8rFCoUAqlaIbBlgVbu01MBISisFYw9+9Dk9OPMddc0Dp5ofTkcOaFhcXs8aY91T17WKx"
    "mP7yxpu8/MRbhGIJxWJVuO21OH7sJL+2r3Ptt2//DCxzEY5QKpXOABe/sZdf6wWGngR0w4BH"
    "TzzOM6fn+Ll1ne/q1+4ElrN3LnPjPwsOWVhYmBORj0SkD/ji6l/vlJ8+9Xzyh9+/3zYRzu58"
    "Sv3+M/0fJi/hW40le9jTu59x83D+DyVusCmsaHTtAAAAAElFTkSuQmCC")
getBrick_GoData = Brick_Go.GetData
getBrick_GoImage = Brick_Go.GetImage
getBrick_GoBitmap = Brick_Go.GetBitmap

#----------------------------------------------------------------------
Brick_Go2 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAnhJ"
    "REFUOI2Nk81LFHEYxz+7O7O6gjM7GWu+BUbLKouHoEN2EILs0lEiirRrdOkQRVjHLOrQXQ8F"
    "K9luupf+BC/hoWDIzWRBhxXfDjIO24ruOL+nQ225vkCf4/Py/X758XtCHMPs7OyL7e3tEdd1"
    "2wEsy1qLx+OZgYGB0ePm68jn84lcLleVQ+RyuerU1FT74flQzdHzvFuu654FwqZpkkwmSaVS"
    "iAgLCwssLS3heR6AsiyrZJrmh7+Jstns7kE3x3FkZmZGbNsW27ZlenpaHMepS5TNZncBIvl8"
    "/p2maRdFhJaWFkSExcVF9vf3cRyHzc1NDMMgCALa2tpQSlEoFPA8TxscHExpSqk7fX19VCoV"
    "bNsmEomwurrK0NDQ4behqakJ3/epVCrE43G2trZuhIFKR0cHnZ2dmKZJc3MziUSCYrGIUgql"
    "FMVikdbWVqLRKK7rUq1WsSwLEaloIgJAY2Mjuq5TLpfRdR3P85ifnwfA930evXcAh7GbZ4iE"
    "dEQEESGslAJARFBKEYvF6OrqwjRNGhoaKJfLuK4LQH9Pmqe5DfZVlSAIUEqhBUEQC4fDiAi+"
    "7xMEAb7vM/Jm7sgfSbYBpHn2scDrkShKqUYNmJ2bm7uaTCYxDIOdnR329vYAGLmSrhMorv8T"
    "eZwpMJT++UXTdf36ysrK3VKp9Li7u/t8KpXCMIy6pZNE8gUuh2qNTCaT8H3/gYjc7+3tjT+c"
    "XDoxQXEdPv8oUDo1fCHEISYmJtLA6NuvsdsH6/096bplxxpOb7zk+xGBGuPj49eUUk+UUlHg"
    "1eQ341N/T/q38+nhnrXnLMKfY/ofLt2bFIDlluFzm2Ms1+q/AHJLYifAV0AeAAAAAElFTkSu"
    "QmCC")
getBrick_Go2Data = Brick_Go2.GetData
getBrick_Go2Image = Brick_Go2.GetImage
getBrick_Go2Bitmap = Brick_Go2.GetBitmap

#----------------------------------------------------------------------
Bricks = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAtdJ"
    "REFUOI2lk01oXGUUhp/z3b+ZuTNtE0ubdDpQaR2bCaONllSQ4koEN4rgyoWgUhEVofsw1J2g"
    "YDeCQheFrrKsG4tpwErBiFbiD9ZixpAEa/Mznczcn7lz73c/FzEUIq58l4fDc855eQ/8T8ne"
    "wnetVinKw6kkTI6d3A6umKC70+jv4/Zo5VXPKSyVXP+H0xcuRAD2XoAa9Ocbg+yMSRJyk+M9"
    "/ChkGUlng1Oxviw6ZVn3FoCnANReQHl1Zdqt7KM8OQWuQ3/5Dv21NrgO5ZOP4foVysu/T395"
    "/u06gN36tFUKk3Aqy5Jj3hG54s62UfU64bffIKnm4NPPAtD75Xv6P91CpzElUZIruwRgp040"
    "P1ItnElSxTBLEKVw9o8ijUminxcJ27dBDFkQoRyFEgvkweJqW+5Pl9wSJw4fx1YOYu34alAU"
    "J5rYR2tknQ7KUciu5yZ/ABiSyONHn2Qr6JAZzVDZ9K5dBQST56A1xpidyUAa9Qj10MwVH3mo"
    "1bpasi2x8AtlGkeaVPd3mX/pABM3lqnd+AL/wCGKk00s22U4iBnE26yMHOar+suSjVTnNtdX"
    "F2wRRZalDLMEz/Eo12p8fnaTwuJpnv/zJtWb19G54a9ikbn6c6yMTTJx/BDZ/ZB2YE/bSotZ"
    "798TbTRaZyQ6JTc5izLOE2++z7VfV1nrJDTq4/gAS+v81t5gkKRYblFsp1t85vrC/CwVM9as"
    "NfE9H9tyUUooFzwaJ6rUwoQ/NgJ64ZAoSbFFULaFUv9E2Rgj711897XYCS86FeUbk3Nv6UXO"
    "vXCKrX6MAqJhxtc/rkFuEEsQUXS78U6URcQAl4BL5z88d3CrnwW2pNHdTiAGIdeaQZqjtcFx"
    "LIzJCfoD0jgy/3qmXb0x88nZSJdmc290bKoxTrnocuvOOnEypN+NKOTdzYqJXvlPwO5pb818"
    "9non8z6mMOpnuYZ4O66oYObyB+98BPA3aMRFSJfpxxsAAAAASUVORK5CYII=")
getBricksData = Bricks.GetData
getBricksImage = Bricks.GetImage
getBricksBitmap = Bricks.GetBitmap

#----------------------------------------------------------------------
Tag_Blue = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAihJ"
    "REFUOI2NkM1LW1EQR8+9+epru7CEZ4x5qVghpSJKsxKzKqUUXHTpqov+Z4UuhUAtGJBAWgIN"
    "uLBFgljl+Vo1EUxiFOJHNHlzuyimWjX0BwMXhnPuzKi1tTVjjEFEMMZw9a2UGkyn03X6pVwu"
    "G9/3b1SlUjErKyumWCza/XhtjAGgWq2yurrK7u4uAPF4HNu2sSyr1k+iRQSAer1OOp1W+/v7"
    "305PTxEREokEtm0TCoXulPQE0WiU5eXlcxGxg8EgB234sgfJZJJYLIZS6lZJ8HKFZDKJ4zjh"
    "TqeTbEmYD67i3FcYI7wYGUFEqFQqtVwuNzg7O1u/OsFZs9kEQEQ46gZ5v6F4GFLELPh+oPlc"
    "hdHRUYaHh4lEIrVcLtebRPu+/9p13bNGo0EgEKDRhgtRaCCoYSDyVzI2NobjOAQCgZ5EAZRK"
    "pUy3282nUinLtm02DoVP25qBe5qwBt9Asw3Po8JLBzY3N/E8j5OTk0ENMDMz8xV4tb6+flar"
    "1Xj6SPNmRDhqCxfy55eQhnL9AjGgtb6s++rqRQuFQsb3/fz4+Lg1NDTExqHwcVsT1poHusPb"
    "lGFv5xee59FqtZ7Mzc39vCYAWFpayhhj8hMTE1Y8HufHoVDc07x7Bjueew3u3eDfLC4uZowx"
    "+cnJSSuRSADgui5bW1scHx/34DsFAAsLC9NAYWpqymq323iedwPuKwDIZrPTQMGyLOs2+L+S"
    "zWan5+fnH9/V/w2LODSct0nVfgAAAABJRU5ErkJggg==")
getTag_BlueData = Tag_Blue.GetData
getTag_BlueImage = Tag_Blue.GetImage
getTag_BlueBitmap = Tag_Blue.GetBitmap

#----------------------------------------------------------------------
Tag_Green = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAlBJ"
    "REFUOI2NkUtrE2EUhp+Z3JwWrBAnbXNRYrGLIAlkVRoFNyJk40IoLv0L/gLXLvwHIi4EIZBF"
    "hKSthSxiLRRJIZQ2tE3HSyetTWKqNFeT+T5XDZW0wQMHDpzzPuembG1tSSklQgiklJyPFUXx"
    "RKPRKqNsc3NTWpY15KZpynw+L3O5nD5Kr0opASiXyxQKBQ4ODgCYnp5G13U0TauMgqhCCACq"
    "1SrRaFQ5Pj7eaLVaCCHw+Xzouo7D4bgUMgC43W7W19e7QgjdbrdTb/xgdfs9gUCAyclJFEW5"
    "EGI/WyEQCOD3+529Xi/Q+HPCu9WXdHttJJJ7oUcIITBNs5LJZDzxeLx6foJ2vV4HQAjB73aN"
    "t7kXjF+5iuean8LXHB+3UwSDQbxeLy6Xq5LJZAaTqJZlPSyVSu1arYbNZqPeOKLX76AqKnbV"
    "wcT49QFkZmYGv9+PzWYbQBSAtbW1WL/fX5mdndV0XWfvsEBm4w3Xxt047C4s0eekUSF88y73"
    "7zxmd3cXwzBoNpseFWB+fv4T8KBYLLYrlQq3vRHi0af8av6k1++iKCoOu5Ptb58R0kJV1TMf"
    "U85fNJvNxizLWgmFQtrU1BR7hwXS+dc47E7GnBM8iT2jbB5hGAanp6e3FhYWvgz9dXl5Oba0"
    "tNQyTVNaliWL3/Py1Yfnst1tyZ2dHbm4uCgTiUTwrF4ZIgDpdDompVwJh8Oaz+cDoFQqsb+/"
    "T6PR+KfzhQCAVCo1B2QjkYjW6XQwDGNIPBIAkEwm54CspmnaReL/smQyOZdIJG5clv8Ly4ZK"
    "eEm+RpsAAAAASUVORK5CYII=")
getTag_GreenData = Tag_Green.GetData
getTag_GreenImage = Tag_Green.GetImage
getTag_GreenBitmap = Tag_Green.GetBitmap

#----------------------------------------------------------------------
Tag_Red = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAixJ"
    "REFUOI2NkN9Lk1EYxz/n/aG8GijIO53bChO9GDJjV+KI6iKC0bUU0T8XRSDswmgvyGDQUsEL"
    "oyFLmq9voVvgpitx/pznnC7EoamjLzxw4PD58H0eUSqVtNYapRRaay6/hRChZDJZp1NWV1e1"
    "lPLaVCoVvbKyoguFgtuJN7TWAFSrVYrFIltbWwCEw2Fc18VxnFoniaGUAqBer5NMJsX29vaX"
    "w8NDlFJEIhFc18W27VslbcHAwADLy8snSinXsixo7CIXCsRiMQYHBxFC3CixLlaIxWJEo9Gu"
    "VqsVs5tN1Pt3cHKK1Jp7Dx+hlKJSqdQ8zwul0+n65QZHjUYDAKUU1t4e6u0bRO8dRCgExa/I"
    "z58YGRlheHiY7u7umud57SaGlPKZ7/tHOzs7mKaJbuxC6xQMAywL0dffloyOjhKNRjFNsy0R"
    "AEtLS6mzs7Pc+Pi447oucn0d7X3E6O8DuwukRP9uQOIB5uMnlMtlgiDg4OAgZABMT08vAk/X"
    "1taOarUa5tgYIv0c9WfvvI0QYHdx8q0ESmEYxsX0iMsXzefzKSllLh6PO0NDQ+dNsh8Qtk2r"
    "pxfrxUt+Vn8RBAH7+/v3Z2ZmflwRAMzPz6e01rmJiQknHA4jy9/RiwtYr17jb25egds3+DfZ"
    "bDaltc4lEgknEokA4Ps+GxsbNJvNNnyrAGBubm4KyE9OTjrHx8cEQXAN7igAyGQyU0DecRzn"
    "Jvi/kslkpmZnZ+/e9v8XZxo6vzFHBpoAAAAASUVORK5CYII=")
getTag_RedData = Tag_Red.GetData
getTag_RedImage = Tag_Red.GetImage
getTag_RedBitmap = Tag_Red.GetBitmap

#----------------------------------------------------------------------
World = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAz1J"
    "REFUOI1dk0toXGUAhb//PubOJDOZTF40CdPEGtrQmtrGRINpAwVrVhUKUhQFX5CVunLfjRBw"
    "40KJCwUrCEUCxYXQUquhppbGxsRIbIyTGqOZpMk4M5mbzJ37+O/93VhpPavD4ePbHcH/8uaN"
    "V08KxFsoBhG0CpSBEhUEMyqKJj4Y+ezKg7y4X85PnTfKxtoFBM+fyZ62MolWbKcexwcZuki2"
    "uLZxWUah/Now5bmJU5N7/wnGZsfMuBtMDbQcGX42ewrbtfDwWbEFMWVRdCKU9EngsOlNczt/"
    "+2dP6iOT5yYrGoDlBhf6mw8On+gYoBT6BJpASo2ajOEQo+RZbLsJ1ism+5NPMtjeezR0qxcB"
    "9LenXzshUO+9dPCMvhhW2aRGLZLsuUlKnontQi6/S6VaxcoUEekcQy29fHNn5kDP6P4F/ak3"
    "jr8/2jn0mNATbGoSVBvtYZIft3Rqrsad/B5RvIzVtYzXkKMQlTHKIX3NWW127dcmQ8FgtqGT"
    "n5wNCnGNw/qjREjWtn1ct0Z6n8JuuspKtAOeolFa5Aoez3T3E3iyzxBKNdcZ9aw5G2x7Dqm6"
    "A+z4KcrliHSrS1vGoRAew/YWsNQuu38XKe3UkUykCDzZaEQKIRT4no0ii2GGXL4VIBJJNlck"
    "mmqgo7VGavckdj7AZZbAXwWlCKQURhSGJdu3O5v1RlLxx1kvGLiBSSxuEW9LcPf3Iu4PjRC5"
    "pNtMGus7SevblKsVwlBVtCAI5/4o/UlPXZaN7e+JzDwx3SNwHYLAIJbMYDXFMeIapgjR/QId"
    "7S2sbqyCUkta6IYfXlq6LruSrRhOnkrxJpmMhyE9TKGwNB3D98lk10m3fYdWW+ZYto+Ja5eU"
    "hvaxPn/xl7u9Z3sGvFr10BPthyk5DnHrEaKagWWZmEJiygrp+q/gXpH+I73M5xbJ3fvr+tz4"
    "wjsGgLsnXp76bf6GV/OPjh4fYXnbQK8opNgliDRIhmS7ujnU1823cze5snArZwTyxYfO9Nwn"
    "T6eqtv5FIOXpV4ZfNwj3oVQdQhO0pG22SnN8dPXLEMV0jOiFmfHFrYcE9zP07uDZSEZjYRj1"
    "RTLM/DtXQCwBn86PL3z+IP8PibCT70syInMAAAAASUVORK5CYII=")
getWorldData = World.GetData
getWorldImage = World.GetImage
getWorldBitmap = World.GetBitmap

