###############################################################################
# Name: FileIcon.py                                                           #
# Purpose: Icon resources for filebrowser                                     #
# Author: Cody Precord <cprecord@editra.org>                                  #
# Copyright: (c) 2007 Cody Precord <staff@editra.org>                         #
# Licence: wxWindows Licence                                                  #
###############################################################################

"""
FileIncon.py

Pixmap resource file

"""

__author__ = "Cody Precord <cprecord@editra.org>"
__svnid__ = "$Id$"
__revision__ = "$Revision$"

#----------------------------------------------------------------------
# This file was generated by /usr/local/bin/img2py
#
from extern.embeddedimage import PyEmbeddedImage

Image = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAABVxJ"
    "REFUWIWtl31MVWUcxz/n7Z4rL4FFCJoIKIyBIRRhXhSUkD/QuebaWqv+o5Vt2mZ/tGq2Zhv9"
    "YUSrWc3NuUrnZkS1Cai3pkVaoaWQLxjyqitI4CJwX+Cee29/wLmdezn3ciuf7dlznuc85/f9"
    "PL/f8/zOOQLmRYgwHmmuCATm+v65NmA+PbTIZgavXr26Py0tbUcgECAQ+MeOfq2P61UURSYm"
    "Js7m5ORsBnyAFiuEaDIm9fX1LXK73Xg8nmB1uVy43e6Q1uVy4XQ6GRsbw+PxlHV2drpqamrK"
    "gEWARAyeNAMQNU1TRFFEEAT0NloVxVkzMzMz1NXVfVteXl4OxDPr4agQZgAAIQIARiC9L4oi"
    "kiQhiiKyPBtNh8MhNDU1NZeUlDwG3LMQhCmALmQUi7Z6WZZRFAVJkvB6vcTHxwutra2NRUVF"
    "1UByNAhTAF0wXDwcSO9LkoQsy8iyjCAIDAwMkJKSItjt9iNFRUVV0TwRNQRGoYW8IYoiiqKg"
    "qio9PT20tbXh9XqF06dPHyktLd0AxM3phUBEDIHRcDRv3Ort5ocTx4MACQkJiKLI4OAgp06d"
    "wm63C/X19U0VFRXrAMscQBDCLA+ECPn9/qBgIBAIjrWfsSNJEolJiymv2TZrTJZJTExEEAQS"
    "ExPxeDy6HaG+vr61pKQkldkcoQW1IoXAzOX6td/v42TjUaYmxvmu+Ut2bq8mEAggSRKqqpKc"
    "nExqairp6emkpKQQHx+PLMvY7fZ3CdsLET2gt3r201cOoCgWVheXYKvagq1qC7UWC0DQQ/qm"
    "tFqt+Hw+NE3D5/MxPDyshyCYIU0BjC43iutjQzcHSM/MxhoXF4SKNFe3pWmanitC0rMpgG7I"
    "zCBAekYmQ4P9HNq3l/7fu7jScYlHKzezu65h3lzdjqIoKIoSmAMIQix4DPVQBDfl2DjlNhs7"
    "d73MhrJqdr3dwIGv7PjuSaNyXRmNn35mmjfmaoh4RIDwc+8Y+QtBEJi63EXtizvIzc9nVeGD"
    "1L7+Kr5hB0kuLz9dOM/K1fl8caKF7l8vmcKblYh7QK/OyQmOffw+HRfPs3RJLnkPFZOdnY3H"
    "4yG/u5fugQGs96VSsbGCzIwMRkcd7P/kEO9kZfLCU1t5Zd8HrCxYE7KoBQGMEDPT0/x45huS"
    "rfEEFlnJWbWKTZWVjIyMcM7tQQ748TrukF9QQNXGTfx2+TJDw0P0dVyisOQRLKoVSZKC+SQm"
    "AKPb7r0/lYajX+N1uvj58Oc4XG6GhoaYmpzE6XFzres6KcuzGJc0um/0MDo6xoTLiZaUxLZn"
    "nyMrryD40RJzCMLDsGTZcpwuJzm5ORxuP8ftsVFmpqfp6uoi15rAeFwy7b1XuNnfj8UzQ2VW"
    "DmvWrsXv9wePYiSImL4HBEFg4Po1jp1sxJawmOvtFzje0sL3bW2oosTE5ATNLc1cPHsO560/"
    "yCtcQ1fHL8G4h79TFgQw5gC95hQU8kB+Prnbqtnz5DPU5BawvdTG+uKH8Xi9PG2roLZiM7vf"
    "fIPeP2/QdPAjNK83qnhMIdATikVV2fHaXgD8a/3sebwGyaLQ39fL+Q/f462DBxBVC36/n/VJ"
    "Wym2VWBR1dn5c9ky5hDoE43U4SGRVQuCIHCkoY6ua53cvj0UvJeYvJgly5bPS0QxnwL9IX0D"
    "6QDh6RXgiedfYurOOEtXZM17B4SnZbMSEcC4cuNODgfIW10YMjf82Uj3YgIQRXHeqoxQkUTM"
    "3oh6P2YAozHjWDRvRFvxf/KAUfRueONfbUIz+v/rjZhDkJCQoMQKEslwFLshR8IsMJKqqitk"
    "Wc5g9gfzbhWfpmmD09PTgxi+iv8G6rxBe3k5OiEAAAAASUVORK5CYII=")

